apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hostuser-rb
subjects:
- kind: User
  name: hostuser
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: hostuser-role
  apiGroup: rbac.authorization.k8s.io