apiVersion: apps/v1
kind: Deployment
metadata:
  name: bb-myool
  labels:
    app: depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: depl
  template:
    metadata:
      labels:
        app: depl
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["sh", "-c", "while true; do echo 'I am busy' >> /input/data.txt; sleep 5; done"]
        volumeMounts:
        - name: my-volume
          mountPath: /input
      - name: multitool
        image: wbitt/network-multitool
        volumeMounts:
        - name: my-volume
          mountPath: /output
      volumes:
        - name: my-volume
          persistentVolumeClaim:
            claimName: pvc-volume